#!/usr/bin/env python
# -*- coding: utf-8 -*-

from subprocess import Popen
from urllib.request import urlopen
from os import makedirs
from zipfile import ZipFile, extractall

# git
# repository, plugin name
git = (
        ('https://github.com/msanders/snipmate.vim.git','snipmate'),
      )
# plugin name, src_id, type/directory
vimorg = (
        ('python-complete','10872','autoload'),
        ('buffer-explorer','14208','zip'),
      )

def git_clone():
    global git
    for arg in git:
        # FIXME: use os.path.join
        cmd = 'git clone ' + arg[0] + ' bundle/' + arg[1]
        Popen(cmd, shell=True).communicate()

def download_vimorg():
    global vimorg
    for arg in vimorg:
        # FIXME: use os.path.join
        if arg[2] == 'zip':
            filepath = 'bundle/' + arg[0] + '/' + arg[2]
        else:
            filepath = 'bundle/' + arg[0]
        makedirs(filepath, exist_ok=True)
        url = "http://www.vim.org/scripts/download_script.php?src_id=" + arg[1]
        u = urlopen(url)
        filename = u.info().get_filename()
        # FIXME: use os.path.join
        fullpath = filepath + '/' + filename
        print('vim.org: ' + url)
        print('Downloading ' + filename + ' into ' + filepath)
        with open(fullpath,'wb') as f:
            f.write(u.read())
        u.close()

        # check file type and do additional actions
        if arg[2] == 'zip':
            with ZipFile(fullpath, 'r') as myzip:
                myzip.extractall(filepath)

#git_clone()
download_vimorg()
